name: ${projectName}
main: com.spinalcraft.chunksblow.ChunksBlow
version: ${projectVersion}

commands:
  chunk:
    description: Manipulate chunks to be deleted.
    usage: Usage - /chunk <report | unreport>
    permission: spinalpack.chunk
    permission-message: No!
