name: ChunksBlow
main: com.spinalcraft.chunksblow.ChunksBlow
version: 1.1.0

commands:
  chunk:
    description: Manipulate chunks to be deleted.
    usage: Usage - /chunk <report | unreport>
    permission: spinalpack.chunk
    permission-message: No!
